kumuluzee:
  streaming:
    kafka:
      producer:
        bootstrap-servers: localhost:9092
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: com.kumuluz.ee.samples.catalogue.fressian.FressianSerializer
        value-serializer: com.kumuluz.ee.samples.catalogue.fressian.FressianSerializer
      streams:
        bootstrap-servers: localhost:9092
        application-id: catalogue-app
        default-key-serde: com.kumuluz.ee.samples.catalogue.fressian.FressianSerde
        default-value-serde: com.kumuluz.ee.samples.catalogue.fressian.FressianSerde
        commit-interval-ms: 0
        cache-max-bytes-buffering: 0