kumuluzee:
  streaming:
    kafka:
      producer:
        bootstrap-servers: localhost:9092
        acks: all
        retries: 0
        batch-size: 16384
        linger-ms: 1
        buffer-memory: 33554432
        key-serializer: com.kumuluz.ee.samples.shipments.fressian.FressianSerializer
        value-serializer: com.kumuluz.ee.samples.shipments.fressian.FressianSerializer
      consumer:
        bootstrap-servers: localhost:9092
        group-id: shipments-procesor-1
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: com.kumuluz.ee.samples.shipments.fressian.FressianDeserializer
        value-deserializer: com.kumuluz.ee.samples.shipments.fressian.FressianDeserializer
      streams:
        bootstrap-servers: localhost:9092
        application-id: shipments-app
        default-key-serde: com.kumuluz.ee.samples.shipments.fressian.FressianSerde
        default-value-serde: com.kumuluz.ee.samples.shipments.fressian.FressianSerde
        commit-interval-ms: 0
        cache-max-bytes-buffering: 0